create table Person (
                        person_id int generated by default as identity primary key,
                        name varchar(100) not null unique,
                        year_of_birth int not null
);

create table Book (
                      book_id int generated by default as identity primary key,
                      name varchar(100) not null,
                      author varchar(100) not null,
                      year_of_release int not null,
                      person_id int references Person(person_id) on delete set null
);

select * from person